koda-momo/ec-202110b

- package-lock.json
- src/views/cartList.vue
- src/views/itemDetail.vue
- src/views/itemList.vue
- src/views/login.vue
- src/views/orderConfirm.vue
- src/views/orderFinished.vue
- src/views/registerAdmin.vue
> Vueファイルを作成

- src/types/User.ts
> Userクラスを作成しました

- src/components/Footer.vue
- src/components/Header.vue
> ヘッダーとフッターを更新

- src/types/Item.ts
> ITEMクラスを作成しました

- src/types/Topping.ts
> トッピングクラスを作成しました

- public/index.html
- src/components/Footer.vue
- src/components/Header.vue
> CSSマテリアライズをインポートしました

- src/types/Order.ts
> Orderクラスを作成しました

- class.drawio
・ログインの変数1つ漏らしていました、すみません。
・管理者登録の仕様1つ漏らしていました、すみません。
> 管理者登録／ログインのクラス図を修正しました

- src/store/index.ts
> (index)ストアにカートの中身を削除／追加のメソッドを作成

- src/views/orderFinished.vue
> 注文完了画面を作成しました

- src/store/index.ts
- src/views/orderConfirm.vue
・indexのstoreにミューテーション、stateを追加
・注文確定画面でログインＩＤを持ってくるようにしました
> ログインIDをstoreのindexに置けるようにしました。

- src/views/itemList.vue
> CSSとコメントを修正しました

- src/views/itemList.vue
> 並び順変更機能を作成しました

- src/views/orderConfirm.vue
・クレジット選択時にクレジット情報入力画面を表示
・クレジット用エラーの設定
・クレジットAPIに情報を送れるように設定
★注文番号は後ほどindexのstoreを通して持ってこれるようにします
> クレジットAPI機能を付けました

- src/views/itemList.vue
> 商品金額を3桁区切りに変更

- public/css/item_detail.css
- src/views/itemDetail.vue
> コメントとCSSを編集

- src/views/cartList.vue
- src/views/itemDetail.vue
- src/views/itemList.vue
> 商品一覧へ戻るボタンの追加と画像リンクの追加

- src/store/index.ts
- src/views/cartList.vue
- src/views/orderConfirm.vue
カートの中身リロード問題を解決出来ませんでしたので戻しました。
> 悲しみのコメントアウト

- src/store/index.ts
- src/views/orderConfirm.vue
・コメント修正
・注文後カートの中身を空にするようにしました
> 【テスト前調整】注文確認画面を修正

- src/views/cartList.vue
修正内容
・【高】ショッピングカート価格カンマ区切り
・【高】トッピングの隙間
・【低】カート内0件時のerror表示
> カート内表示機能を修正しました。

- src/store/index.ts
- src/types/OrderItem.ts
- src/views/orderConfirm.vue
・セキュリティコードが123以外の時は弾くようにしました。
・有効期限が過ぎていたらOUTにしました。
> クレジットカードのエラー処理を追加

- src/views/orderConfirm.vue
- src/views/registerAdmin.vue
登録画面／注文確定画面
・郵便番号で住所検索→ラベルを非表示に
・エラーの際ラベルを非表示に
> ラベルの表示／非表示を切り替えました

- src/views/itemList.vue
> 現在のページ数を表示

- src/@types/vue2-flip-countdown.d.ts
- tsconfig.json
先日相談があった
vue2-flip-countdownをインポートする際に出ていたコンパイルエラーについて
解消しましたのでご確認後マージをお願い致します。
> vue2-flip-countdownをインポートする際に出ていたコンパイルエラーを解消しました

- src/views/orderConfirm.vue
- src/views/orderFinished.vue
・注文確定後の文章を修正
・注文確定画面の決済方法の初期値を代金引き換えにしました
> 細かい修正を行いました

- src/views/orderConfirm.vue
> 注文確定画面のAPI送付情報を修正しました

- src/views/orderConfirm.vue
> 注文API修正(再)

- src/router/index.ts
> 商品一覧表ページに遷移するときにページ下部が表示される不具合を解消

- src/types/OrderItem.ts
> トータルプライスの計算方法が誤っていたので修正

- src/views/itemDetail.vue
> お気に入りに追加する機能について、♡→ボタンに変更しました

- src/views/orderConfirm.vue
- src/views/registerAdmin.vue
大文字小文字数字含んでいないと弾きます。
宜しくお願いします。
> 登録時のパスワードの堅牢度を高めました。

- src/views/top.vue
> アニメーションスピードの変更

- src/views/itemList.vue
> 検索時のページ数表示、順を非表示

- src/views/orderFinished.vue
> 注文完了後の三田のスピードを調節しました

- src/views/itemDetail.vue
> お気に入り登録のボタンを修正
